# Generated by Django 5.2.5 on 2025-09-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_application', '0002_alter_category_name_alter_dish_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='', verbose_name='Адреса доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='ПІБ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Онлайн карткою'), ('cash', 'Готівка при отриманні')], default='cash', max_length=10, verbose_name='Метод оплати'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('paid', 'Оплачене'), ('completed', 'Виконане')], default='new', max_length=20, verbose_name='Статус замовлення'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступна'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
    ]
