# Generated by Django 5.2.5 on 2025-09-12 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_application', '0003_order_address_order_full_name_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant_application.dish', verbose_name='Страва'),
        ),
    ]
